---
title: "Wiki Entry Template"
 subtitle: "BA New Media / Online Communication KF/BF A: Spring Term 2023"
 author: "Alina Hahn"
 categories:
- "Digital Media"
---


Wiki Project: What Constitutes Autonomy in Digital Communication?

Digital media use is one of the most talked about topics at the moment and can be linked to different aspects of research. One of the most common areas of research is digital media use and its impact on mental health. There is a wide range of research possibilities and in the following paper the link between digital media use and mental health is explained based on the article ´Computer-Mediated Communication, Social Media, and Mental Health: A Conceptual and Empirical Meta-Review´ by Reinecke and Meier (2021). The authors focus not only on digital media use, but also extend the research to include autonomy needs and computer-mediated communication (CMC).

´Computer-mediated communication (CMC), the Internet, and now social and mobile media have repeatedly been characterised as a blessing or a curse for users’ mental health (MH)´ (p.1183) is the main aspect of the paper. The authors explain the relationship between social media use and mental health with negative and positive examples and highlight the importance of the research area. When looking at the relationship between computer-mediated communication and mental health it is clear, that the two can’t go without each other. The authors argue the importance of addressing both channel-centric and communication-centric factors in the relationship between CMC and mental health. The authors show a CMC taxonomy that differentiates between six levels. They also propose two operational approaches: a technology-centered approach that emphasises technology characteristics, and a user-centered approach that focuses on user behaviours and interactions. These frameworks can help to research more about the complex relationship between CMC, social media, and mental health.

When talking about the theoretical arguments put forward in this paper, Reinecke and Meier base their arguments on different theories such as self determination theory. This theory is a common explanation for autonomy needs in digital communication and creates a relationship between different studies. The paper ´Motives for sport participation as predictors of motivation outcomes in track and field: A self-determination theory perspective ´ from Bhatnagar and Karageorghis (2008) base their study on the same theory and explain the motives for sport participation. The authors claim that autonomous regulations are expected to correspond with positive outcomes and Reinecke and Meier also agree with this statement. When looking at mental health they claim that the self determination theory can be used as a explanation for mental health and user- centered communication approaches (p. 1203). This could be part of future researches, where the self determination theory is the main aspects. Questions like ´Is there a correlation between the need to satisfy the intrinsic motivation and media use?´ or ´To what extend does the need for autonomy and social connection influence media use?´ can be asked.

Another theoretical aspect or more so, the basement of the main paper, is the division into technology-centered and user-centered approaches. This is one of the main argument of Reinecke and Meier when looking at CMC and MH. The correlation between CMC and MH is also the main topic in the paper of Meier, Domahidi and Günther (2020) where 20 years of study is retrieved through a systematic database search. Even though they didn’t divide into technology-centered and user-centered approaches, they did indeed mention different users in the context of how the access to information and communication technologies (ICTs) affects different marginalised approaches (p. 22). This is a expansion to the Reinecke and Meier study and could be an inspiration for further studies. Following questions could be asked: ‘How do the effects of CMC and social media on mental health vary across different populations (e.g. gender, age, cultural or social background), and how can future studies research these differences?’.

After the focus on further research questions, we will take another look at the paper from Reinecke and Meier (2021) to understand the research furthermore. ´Computer-Mediated Communication, Social Media, and Mental Health: A Conceptual and Empirical Meta-Review´ is a comprehensive study that explores the relationship between computer-mediated communication (CMC), social media, and mental health. The authors claim that while there is a growing amount of research on this topic, a more detailed approach is needed to understand the relationship between digital media use and mental health outcomes. To address this, the authors propose a CMC taxonomy and theoretical frameworks that can be used to better understand this relationship and its consequences. The CMC taxonomy distinguishes between channel-centred and communication-centred approaches (p.1185). It identifies four levels of analysis for channel-centred approaches (device, application type, branded application and features) and two levels of analysis for communication-centred approaches (interaction and message). This focusses on autonomy need experiences that relate to digital media use, but it isn’t the primary focus of this article. Individual perceptions of autonomy needs and digital media could be a relevant factor to consider in future.

The theoretical frameworks which connect digital media use and autonomy need experiences draw on self-determination theory and social comparison theory to identify key factors such as autonomy, social comparison, and social support (p.1203). While autonomy is discussed in the context of self-determination theory, the authors note that widespread use of digital media could have both positive and negative effects on autonomy and psychological well-being. For example, they note that negative effects on mental health are depression, anxiety, and loneliness, whereas the positive benefits, such as increased connectivity, social support, and information sharing, are important as well (p. 1189).

The individual perception of digital autonomy or autonomy need experiences and their relationship to digital media use should be more studied. This article does not directly address the topic on it’s own. However, the authors propose a CMC taxonomy and theoretical frameworks that can be used to more effectively study the complex relationship between CMC, social media use, and mental health. The devision into channel-centered and communication-centered approaches may be useful for explaining the relationship between digital media use and autonomy needs, because it focusses on the individual approaches.

Overall, the article provides a valuable contribution to the growing literature on CMC, social media, and mental health, and highlights the need for further empirical work to better understand this complex relationship. The presented study is the base for future research and should be expanded. Literaturverzeichnis

Bhatnagar, T., & Karageorghis, C. I. (2008). Motives for sport participation as predictors of motivation outcomes in track and field: A self-determination theory perspective. The Sport Journal, 11(4). https://bura.brunel.ac.uk/handle/2438/4654

Meier, A., & Reinecke, L. (2021). Computer-mediated communication, social media, and mental health: A conceptual and empirical meta-review. Communication Research, 48(8), 1182-1209.

Meier, A., Domahidi, E., & Günther, E. (2020). Computer-Mediated Communication and Mental Health. The Oxford handbook of digital technology and society,
