---
title: "Wiki Entry Template"
 subtitle: "BA New Media / Online Communication KF/BF A: Spring Term 2023"
 author: "Marie Kreischer"
 categories:
- "Digital Media"
---

Wiki Entry Source:

Meier A. (2018). Alles eine Frage der digitalen Autonomie? Die Rolle von Autonomie in der digitalen Kommunikation für psychologische Grundbedürfnisse und psychische Gesundheit im Alltag [All a question of digital autonomy? The role of autonomy in digital communication for basic psychological needs and mental health in everyday life]. Medien & Kommunikationswissenschaft, 66(4), 407–427. Crossref

Key Quote

„Die hier präsentierte Studie nimmt sich der Frage an, ob die Befriedigung vs. Frustration des Autonomiebedürfnisses in der interpersonalen digitalen Kommunikation dabei einen relevanten Einfluss auf die psychische Gesundheit hat.“. Starting from this quote found in the conclusion of the article, the main argument of Meiers study can be deducted.

Main argument

Meier states, that the feeling of autonomy experienced through the use of digital media, e.g. messenger apps, can impact the feeling of well-being in other parts of life except the digital one. Autonomy is identified as one of three basic human needs that are essential for well-being. While the presence of perceived autonomy leads to a feeling of well-being, the absence on the other hand can lead to frustration, stress and even higher the risk of psychological diseases. Other than autonomy, feelings of connectivity and competence have a similar effect on a person’s mental health. Differentiating his study from others, this study also prioritizes focusing on positive outcomes concerning autonomy and digital media, stating that choosing when and where to interact with others can positively influence the feeling of autonomy. The feeling of being overwhelmed however, for example when receiving too many messages at once or being distracted from other tasks, can lead to autonomy frustration. This was also found by many other studies. As another argument, Meier connects the need of autonomy with the feeling of authenticity, stating that autonomy and authenticity are deeply connected and result in similar effects. Describing authenticity as a state of well-being, where the person can be themselves and is therefore comfortable with themselves.

Relation to other articles

This main argument is based on the “self-determination theory” (SDT). A theory, that defines personal well-being as something that is made up by basic needs like motivation, self-regulation and the social environment of the individual. Meier’s study goes more in depth with one sub-theory of the self-determination theory, focusing on three psychological basic needs of humans: connectivity, competence, autonomy. These three traits building the basis for psychological well-being. This study being the first to transfer this psychological construct to media research. Possible positive outcomes of experiencing autonomy while using digital media could also be found in other studies. Though these primarily focused on a work related environment but with autonomous motivation. Other studies have focused more on the negative effects that occurred after the feeling of autonomy could not be satisfied. Therefore negative effects occurred especially after media use led to neglecting other duties and thus interfering with other goals. It is also supposed, that positive and negative outcomes can occur simultaneously, as causes for both cases are different.

The study uses many of these findings as a basis. It further adds to a mixed field of opinions within the research. While some researchers have found that interpersonal digital communication (on Facebook) has indeed fulfilled the feeling of autonomy to a high degree, other researchers have come to different conclusions. Thus stating, that a felt overload of communication, a use of many digital communication platforms at once or an unwanted interruption from something else can induce stress and the feeling of autonomy-loss.

Considering all of the aspects mentioned above, this specific study adds to the knowledge and connection between digital media use, specifically in communication, and the importance of experienced autonomy. New insights are being formed by focusing on individual and private communication via digital media, whereas prior studies had primarily focused on the aspect of felt autonomy and digital media in a work related environment. Additionally, this study differentiates between autonomy frustration and satisfaction, something that has also not been done in many studies before. Going from there, with the findings of this specific study, many others can build upon that knowledge and go further in depth. For example examining the key factors leading to experience of autonomy loss or other questions raised by the study, as can be seen in the following paragraph.

Questions raised by the study

Whilst the study answers some questions concerning the positive and negative impact of satisfying the feeling of autonomy within digital media, it does not answer, what exactly triggers the feeling of autonomy loss. This however was being done by other studies following. As an example, the study done by Gilbert et al. (2022) can be mentioned. The scientists first of all supported the main finding of this study, confirming the loss of autonomy while using digital media to enhance stress in real life, worsening the overall mental health of the user. This was especially the case, when there was a big communication load on the user. This however was not connected to being connected on several platforms at once. Gilberts study being a good example building upon the knowledge formed in this study, as was already mentioned above. Going further in depth with this first question raised, a follow up study done to examine further media development on that field would also be interesting. How does the new development of AI for example influence experienced autonomy when using digital media as it becomes smarter and more self-functioning?

Another question raised is why people still use digital media, even if it enhances their stress perception and deteriorates their overall well-being. This being rather in the field of general media usage research.

Summary

Generally, the study connects digital media use and autonomy need experiences through the “self-determination theory”, more specifically the sub-theory of psychological basic human needs. It therefore states that through the autonomous use of digital media, one is able to fulfil a basic human need. The theory emphasizes the importance of the feeling of autonomy, stating that the unfulfillment of that need could even lead to mental health issues and stress. On the other hand, the study showed a significant connection between autonomy satisfaction and wellbeing, putting well-being in a similar context to authenticity.

While doing so, the studies also stresses the individuality of the concept. It states that the same influence can have different effects on individuals depending on personal environment (e.g. network size or number of communication partners), individual personalities or the kind of communication happening. Other than these aspects, effects can vary depending on time and situation of the user. Thus the study acknowledges that personal digital communication does not only happen on one platform, but actually occurs on a number of different medias, recognizing that the satisfaction of autonomy need can be influenced through an extreme number of communication requirements on various platforms. The study thus primarily focuses on individual effects of autonomy needs through digital media on mental health.

The study extracts hypothesis out of previous studies and attempts to answer these through a five day diary-study. Only college students (N=532 people) participated. The diaries conducted the overall satisfaction of needs (connectivity, competence, autonomy) and the authenticity experienced, as well as experienced feelings of stress. The (dis-)satisfaction of basic needs was conducted through 5 point Likert-scales, with 3 items concerning the satisfaction of digital autonomy and 3 items concerning the dissatisfaction of digital autonomy while communicating privately via digital media. All three basic needs were also queried through one item, not concerning digital communication but everyday life. All items were tested through a multilevel analysis.
