---
title: "Wiki Overview"
subtitle: "BA New Media / Online Communication KF/BF A: Spring Term 2023"
author: "Julia Kettenbach"
category
- Digital Media Use
---
"(K) Key Quote:" 
“Our results underline that research interest in CMC and mental health has increased dramatically in the last ten years. […] a likely explanation for this is […] societies‘ and researchers‘ concerns surrounding their potential impact.”

"(A) Argument:"
The article provides a detailed description of the methods used to conduct the research, including the search process, inclusion and exclusion criteria and the use of topic modeling to structure findings and manual coding techniques to analyze the selected articles. This study uses a computational scoping review which aims to identify and analyze the interdisciplinary field of Computer-Mediated Communication and Mental Health. The extended two-continua model of mental health integrates the two perspectives – psychophysiology and personal well-being – and is being used for this broad literature review. Various relevant topics and themes are identified, including the effects of social media use on mental health, the potential of online interventions for mental health treatment, and the role of CMC in addressing mental health stigma. Findings show that research on CMC and MH commonly focuses on the negative effects only; however, the authors include further research areas into their review. They consider which potential positive effects CMC can have on MH and how it can support a person. In their work the authors highlight, that there are various alternative approaches to the research field of CMC and MH. The themes chosen for this study include a more detailed approach that looks not only at how CMC can affect mental health, but also how mental health can be an indicator rather than a result of CMC. Overall, the study provides valuable insights into the current state of research on CMC and Mental Health, helping to identify promising research directions and areas where research is limited. The authors call for further interdisciplinary research to address the research gaps identified and to look at the full MH spectrum when doing their research instead of using a one-sided approach.

"® Relationship:"
To put this article in context with other findings in the research field, an article by Meier and Reinecke (2021) will be briefly looked at. 
Meier et al. (2020) used the extended two-continua model of mental health created by Meier and Reinecke (2021) to conduct their literature review. Building on previous models, the idea is to integrate both perspectives; the psychopathology (PTH)  and psychological wellbeing (PWB). Thus, the model considers the positive and negative sides of mental health in relation to CMC. PTH refers to a dysfunction in behaviour of a person’s psychological functioning whereas PWB states how well a person is doing and their psychological function are working optimal. The authors claim that PWB doesn’t mean the absence of PTH and the other way round.  However, different individual and environmental influences affect PTH and PWB, which is why they also have a variety of unique indicators that fluctuate. Furthermore, Meier and Reinecke (2021) integrate “main dimensions and manifestations of both PTH and PWB, as well as risk and resilience factors, in an Extended Two-Continua Model of Mental Health’ (p. 1190). This model allows mental health indicators to be identified across a wide range of mental health research.
Both articles use different approaches to structure the analysis; Meier et al. (2021) define multiple levels at which CMC can be analyzed. Firstly, the devices that Users use to communicate plays a role. The second level analyses the types of application that SNS provide such as emails or messages and another level analyses brands separately. Fourth level analyses CMC channels individually by their features such as Facebook’s status update or Instagram’s photos. Lastly the interactions and individual messages get looked at. The other article separates the analysis into the following nine core topics; Internet addiction and problematic Internet use, Facebook and SNS, Mobile and Smartphone use, Relationships and CMC, Chatting and texting, Cyberbullying, ICT adoption, Work-related SMS and lastly ICT use and sleep. Due to these different focuses in research results may vary or emphasize different aspects. 


"(Q) Questions:" 
1.	Which are further connections between CMC and MH that should receive more attention in future research? 
2.	What role does autonomy play in the impact that CMC can have on MH?


"Summary:" 
The content analysis by Meier et al. (2020) aims to explore the relationship between computer-mediated communication (CMC) and mental health (MH). CMC refers to all social interactions that are mediated by technology designed for information and communication. Meier et al. (2020) conduct their research based on a two-continua model of mental health, assessing both the positive and negative aspects CMC may have on MH. The study applies a computational method that considers a large amount of information, combined with some qualitative research, by searching a meta-data-base of the last 20 years. The research field finds its relevance in the shift to an evolving technological world where social interactions take place online. To structure results, nine core themes were selected in advance, including internet addiction and problematic internet use, Facebook and SNS use, relationship and CMC, to name a few. Findings show that the research field in CMC has largely increased.  The authors found that psychopathology (PTH) is more commonly researched than personal well-being (PWB), whereas a smaller number of publications addressed both sides of MH simultaneously. This can possibly mislead to the presumption that CMC rather leads to mental illness than to mental thriving. Future research should consider whether a one-sided research approach to MH is justified; the authors suggest looking at the full mental health spectrum. Furthermore, they emphasize that different research fields have different approaches to issues; thus a fuller understanding of how CMC affects and is affected by, users’ mental health may benefit from more research from perspectives beyond psychology. Also, more detailed theoretical approaches can show how CMC can impact mental health and how mental health is rather a predictor than an outcome of CMC. 


Meier, A., Domahidi, E., & Günther, E. (2020). Computer-Mediated Communication and Mental Health. In The Oxford Handbook of Digital Technology and Society (pp. 78–110). Oxford University Press. 
Meier, A., & Reinecke, L. (2020). Computer-Mediated Communication, Social Media, and Mental Health: A Conceptual and Empirical Meta-Review. Communication Research, 48(8), 1182–1209. https://doi.org/10.1177/0093650220958224 
