---
title: "Binge Watching and Psychological Well-Being: Media Use between Lack of Control and Perceived Autonomy"
subtitle: "BA New Media / Online Communication KF/BF A: Spring Term 2023"
author: "Niels Iancu"
categories:
  - "Media Psychology"
  - "Digital Media"
  - "Well Being"
---

KARQ-Questions:

(K) "Binge watching provides new opportunities for self-determined forms of entertainment consumption and can positively influence media enjoyment and well-being through perceived autonomy"(Granow et al., 2018, p.9).

(A) The article states that through different media experiences, especially binge-watching, your well-being is positively affected. This relates to the fact that you have an increase in your perceived autonomy through the media use of binge-watching. So an increase in perceived autonomy means an increase in your personal well-being. Self-determination and with that autonomy is an important factor in the relationship between media reception, media enjoyment and your psychological state.

(R) The articles relating to digital media use and autonomy have very similar arguments for the most part. Other articles describe that an increase of choice leads to an increase in perceived autonomy (Schneider et al., 2018, p.171). This correlates to the main article of Granow et al., which states that the choice of being able to select your media content on your own leads to an increase of perceive autonomy. But not all articles are that positive in relation to autonomy and digital media use. They argue that through the control of your attention digital media interferes with your autonomy. This is obviously a wanted effect for social media networks and they use different tools to gain and keep that attention, so this effect of decrease in your perceived autonomy follows naturally (Sahebi & Formosa, 2022).

(Q) 1.Consuming digital media, in this article binge-watching, is said to have a positive impact on your perceived autonomy. But don't you lose part of your autonomy while being stuck in this episode of binge-watching?
2.Does the content that you're watching during a binge-watching phase impact your perceived autonomy, for example, does a TV show that's very thrilling gain more of your attention and through that has more impact on your autonomy?


Summary:
In the article „Binge-watching and psychological well-being: Media use between lack of control and perceived autonomy” from Granow et al., digital media use and autonomy are connected through the example of streaming providers like Netflix or Amazon Prime. They argue that through their seemingly never ending collection of shows and movies you gain autonomy, because you can watch whatever you want, wherever you want and whenever you want ( Granow et al., 2018, p.3). 
The study states that the autonomy effects can vary and depend on the individual autonomy needs or other factors like the media perception of the user, although they also say that normally binge-watching is characterized as having a high degree of self-determination and through that autonomy. That effect can turn negative if an episode of binge-watching goes on for too long, there is no definition of what is too long of an episode though ( Granow et al., 2018, p.4f).
The results of this study show the expected effects of binge-watching on your perceived autonomy, it provides a new and self-determined way of entertainment which generally leads to an increased feeling of autonomy. It also tries to collaborate autonomy and well-being by making the connection that the high self-determination character of binge-watching leads to more autonomy which critically impacts your psychological well-being. Although they specify that to achieve this form of autonomy and self-determination you must balance your binge-watching episodes with other personal goals and standards, so it can have the desired effect (Granow et al., 2018, p.10).
Altogether this article gives a perfect insight to the topic of “Autonomy and Digital media use”, specifying one example and providing context for it. It also goes a bit further in showing the following effects that increased autonomy through digital media use can have, while not relevant for this specific topic it's still interesting insight and can help to understand why this topic is so important.

