---
title: "Wiki Entry Template"
subtitle: "BA New Media / Online Communication KF/BF A: Spring Term 2023"
author: Klara Weißbender 
categories:
  - "Media Psychology"
  - "Digital Media"
  - "Well Being"
---

Key Quote: "The central aims of the present study were...to provide a theoretical and empirical extension of previous research by accounting for the conditional nature of digital stress effects through the introduction of two central situational boundary conditions (i.e., goal conflict and autonomy need dissatisfaction) identified in the mobile connectivity paradox (Vanden Abeele, 2021) and the IM3UNE model (Schneider et al., 2022)"(Gilbert et al., 2022).

Main Argument: The study of Gilbert et al. (2022) shows the importance of situational boundary conditions in regard to the phenomenon of digital stress.The study integrates two recent models -the connectivity paradox by Vanden Abeele and the IM3UNE by Schneider et al.- which both emphasize the effects of digital communication on psychological well-being (Gilbert et al., 2022, p. 6). The study also identified two situational moderators (online vigilance and autonomy need dissatisfaction) of the effects of online vigilance and smartphone use behavior on stress(Gilbert et al., 2022, p. 5).These two situational moderators are significant within-person moderators and were derived from the previous mentioned models (Gilbert et al., 2022, p. 16).The findings of the study provide us with a larger understanding of the situational dynamics connected to digital stress and have practical implications for digital stress reduction (Gilbert et al., 2022, p. 17-18)

Relationship: A lot of studies use the connectivity paradox from Vanden Abeele (2021) as a baseline for their empirical work. A lot of these studies also derive variables from this paper and essentially say the same thing as the study of Gilbert et al.. Most of the time these papers are about psychological well being and perceived autonomy just like Gilbert et al.. For example the study of Granow et al. (2018) deals with these themes as well. But it just chooses a different starting point and deals with the phenomenen of binge watching. 

Questions: Further research should explore whether online vigilance and autonomy need dissatisfaction are the only two situational boundary conditions or whether there are more. And it should be explored if other situational boundary conditions show bigger interaction effects with the two proposed predictors of stress on the within person level.Because online vigilance and autonomy need dissatisfaction only showed small ones. 


Summary: The study of Gilbert et al. (2022) focuses on the mobile connectivity and its negative effect on smartphone users by causing stress. The study tries to throw a new perspective on the research field of digital stress by using the mobile connectivity paradox by Vanden Abeele and the IM3UNE model by Schneider et al. which both assume that digital stress effects could be conditional. Gilbert et al. introduces two situational boundary conditions -goal conflict and autonomy need dissatisfaction- in order to research this assumption.The assumption was split into seven different hypotheses in order to be made measurable.The seven different hypotheses focuse on the investigation of the relationships between the cognitive-motivational (online vigilance) and the behavioral (media multitasking and communication load) smartphone use patterns. In addition the connection between these use patterns and perceived stress is examined against the background of the situational boundary conditions (goal conflict and autonomy need dissatisfaction). The hypotheses are tested based on data from a 7-day experience sampling study. Moreover the whole study design is supposed to address the within-person dynamics of digital stress. The results show that online vigilance can cause stress directly and does so especially through the increase of the communication load. The two situational boundary conditions (goal conflict and autonomy need dissatisfaction) moderate the influence of online vigilance and media multitasking on stress. To conclude the study extended the focus of the between-person associations to a focus on the within-person fluctuations in the context of digital stress. The study also implicates that it's really important to reduce digital stress. Given that online vigilance and communication load cause stress, it seems relevant to establish a conscious management of flows of online communication and make it possible to reduce stress at work and in private. 

